version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    bumps:
      patterns:
      - '*'
- package-ecosystem: pip
  directory: /utils
  schedule:
    interval: monthly
  groups:
    bumps:
      patterns:
      - '*'
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
