#!/bin/bash
cd `dirname $0`
. config.sh
echo "Adding $1 to database"
# mysql -u$SQL_USER -p$SQL_PASS -h $SQL_HOST $SQL_DB -e "INSERT INTO servers VALUES('$1', 'map', '$2', $3, 250, 250);"
# psql -U $SQL_USER -h $SQL_HOST $SQL_DB -c "INSERT INTO servers(name, num, mapfile) VALUES('$1', $2, '$3');"
echo "INSERT INTO servers(name, num, mapfile) VALUES('$1', $2, '$3');" | sqlite3 $SQL_DB
echo "Loading data"
./update.py $1
