#!/bin/bash
cd `dirname $0`
. config.sh
# mysql -u$SQL_USER -p$SQL_PASS -h $SQL_HOST $SQL_DB -e "INSERT INTO servers VALUES('$1', 'map', '$2', $3, 250, 250);"
echo "Adding $1 to database"
psql -U $SQL_USER -h $SQL_HOST $SQL_DB -c "INSERT INTO servers(name, country, num, mapfile) VALUES('$1', '$2', $3, '$4');"
echo "Loading data"
/usr/local/bin/python ./update.py $1
